/// Flutter icons NavbarIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavbarIcons
///      fonts:
///       - asset: fonts/NavbarIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class NavbarIcons {
  NavbarIcons._();

  static const _kFontFam = 'NavbarIcons';
  static const String? _kFontPkg = null;

  static const IconData group_52 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mask_group_1 =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mood =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
